version: '3.1'
services:
  app:
    build:
      dockerfile: Dockerfile
    image: flask-app:latest
    container_name: flask-app
    ports:
      - 5000:5000
    volumes:
        - .:/usr/src/app
    environment:
      SECRET_KEY: 'adsdwarawf'
      MONGODB_CONNSTRING: "mongodb+srv://NGpython:1234@cluster0.tuxio.mongodb.net/Events?retryWrites=true&w=majority"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    volumes:
      - .:/usr/src/app
    environment:
      MONGO_INITDB_ROOT_USERNAME: "NGpython"
      MONGO_INITDB_ROOT_PASSWORD: "1234"
